project:
  type: website

website:
  title: "Quant Play"
  navbar:
    background: secondary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - notes.qmd
      - tools.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



